INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('GPS collar that monitors your pet's location and activity level.', 'Unclaimed', '9/2/2025', '14', '8', '1');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Just add water for delicious brownies.', 'Unclaimed', '11/3/2025', '56', '9', '2');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Leak-proof bottles for travel-sized toiletries.', 'Unclaimed', '8/17/2025', '15', '11', '3');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Refreshing sorbet with a zesty lemon flavor.', 'Unclaimed', '1/10/2025', '37', '6', '4');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Make delicious ice cream at home with this user-friendly machine.', 'Unclaimed', '9/26/2025', '1', '7', '5');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Burr coffee grinder for fresh ground coffee.', 'Unclaimed', '1/14/2025', '48', '4', '6');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Boost your Wi-Fi signal for better coverage.', 'Claimed', '8/12/2025', '62', '7', '7');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Eco-friendly bamboo cutting boards in various sizes.', 'Claimed', '7/17/2025', '22', '10', '8');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Stylish smartwatch with fitness tracking and notifications.', 'Unclaimed', '12/24/2024', '8', '6', '9');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Light and fluffy popcorn coated in sweet honey butter.', 'Claimed', '2/16/2025', '59', '8', '10');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Savory popcorn flavored with maple syrup and bacon bits.', 'Unclaimed', '3/21/2025', '64', '10', '11');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Artisan bread with caraway seeds for added flavor.', 'Claimed', '11/1/2025', '7', '12', '12');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Sweetened powder for refreshing lemonade.', 'Claimed', '7/29/2025', '17', '3', '13');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('High-resolution camera for stunning photos.', 'Claimed', '2/17/2025', '68', '1', '14');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Heavy-duty rope suitable for boating, camping, and general use.', 'Unclaimed', '11/8/2025', '67', '4', '15');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Fluffy couscous seasoned with a blend of herbs, perfect as a side dish.', 'Claimed', '7/11/2025', '70', '8', '16');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Frozen chicken bites coated in a honey sriracha glaze, spicy and sweet.', 'Claimed', '1/16/2025', '76', '4', '17');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Roasted almonds dipped in rich dark chocolate.', 'Claimed', '4/15/2025', '83', '7', '18');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Beautiful wall calendar for organizing your schedule.', 'Unclaimed', '4/10/2025', '34', '1', '19');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Sweetened sticky rice served with fresh mango and coconut sauce.', 'Unclaimed', '7/14/2025', '30', '11', '20');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Marinated chicken skewers infused with traditional tandoori spices.', 'Unclaimed', '4/9/2025', '55', '4', '21');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Juicy pork tenderloin, great for roasting.', 'Claimed', '1/20/2025', '78', '2', '22');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Rechargeable electric razor for a smooth shave.', 'Unclaimed', '11/4/2025', '53', '6', '23');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Challenging puzzle game set for family entertainment.', 'Unclaimed', '10/16/2025', '61', '11', '24');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Complete fondue set for chocolate and cheese parties.', 'Claimed', '12/26/2024', '6', '7', '25');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Frozen mango chunks for smoothies or snacking.', 'Claimed', '3/27/2025', '5', '4', '26');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Crunchy granola mixed with maple syrup and cinnamon, perfect for breakfast or snacks.', 'Claimed', '11/7/2025', '39', '12', '27');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('A fresh salad made with black beans, corn, and a zesty dressing, great for summer cookouts.', 'Unclaimed', '10/16/2025', '95', '6', '28');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Track steps, heart rate, and sleep patterns.', 'Unclaimed', '8/14/2025', '31', '3', '29');
INSERT INTO items (description, status, dateFound, daysInStorage, categroyID, itemID) VALUES ('Compact knife with safety lock for everyday use.', 'Claimed', '4/1/2025', '49', '7', '30');
