INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('1', '6', '4/19/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('2', '1', '11/18/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('3', '6', '8/17/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('4', '9', '4/27/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('5', '10', '10/30/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('6', '2', '5/10/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('7', '9', '8/16/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('8', '2', '6/27/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('9', '6', '10/10/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('10', '8', '5/17/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('11', '9', '8/4/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('12', '7', '12/13/2024', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('13', '2', '9/7/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('14', '7', '12/10/2024', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('15', '2', '1/8/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('16', '5', '2/16/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('17', '5', '1/16/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('18', '9', '12/10/2024', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('19', '8', '1/25/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('20', '10', '7/24/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('21', '3', '5/21/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('22', '1', '3/8/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('23', '1', '10/23/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('24', '10', '2/7/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('25', '9', '9/2/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('26', '5', '8/24/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('27', '2', '1/5/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('28', '5', '1/2/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('29', '6', '9/27/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('30', '10', '10/22/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('31', '5', '7/11/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('32', '6', '11/25/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('33', '1', '4/9/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('34', '3', '5/6/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('35', '5', '11/16/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('36', '1', '11/18/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('37', '1', '6/12/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('38', '3', '5/12/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('39', '2', '10/13/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('40', '1', '10/10/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('41', '3', '9/25/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('42', '6', '9/13/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('43', '4', '11/22/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('44', '9', '11/3/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('45', '8', '2/11/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('46', '2', '8/19/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('47', '9', '6/22/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('48', '8', '6/15/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('49', '9', '5/23/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('50', '4', '12/30/2024', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('51', '8', '7/20/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('52', '9', '11/28/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('53', '1', '7/4/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('54', '6', '1/5/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('55', '9', '11/14/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('56', '4', '2/13/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('57', '2', '1/24/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('58', '8', '8/3/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('59', '10', '9/23/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('60', '5', '7/9/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('61', '6', '2/3/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('62', '4', '3/14/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('63', '10', '6/7/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('64', '1', '5/26/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('65', '3', '12/18/2024', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('66', '8', '1/28/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('67', '10', '3/30/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('68', '9', '3/12/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('69', '9', '7/16/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('70', '2', '3/5/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('71', '10', '9/1/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('72', '7', '3/9/2025', 'no action');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('73', '5', '7/18/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('74', '4', '8/9/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('75', '7', '5/25/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('76', '2', '7/25/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('77', '4', '8/20/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('78', '6', '1/16/2025', 'ban');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('79', '3', '3/31/2025', 'mute');
INSERT INTO moderation (modID, adminID, timestamp, modType) VALUES ('80', '5', '4/2/2025', 'ban');
